INSERT INTO education_degree_titles (`education_level_id`, `degree_full_form`, `degree_initial_form`) VALUES
(1, 'PSC', 'PSC'),
(1, 'Ebtedayee (Madrasah)', ''),
(1, '5 pass',''),
(2, 'JSC', 'JSC'),
(2, 'JDC (Madrasah)', 'JDC'),
(2, '8 pass', ''),
(3, 'SSC', 'SSC'),
(3, 'O Level', ''),
(3, 'Dakhil (Madrasah)', ''),
(3, 'SSC (Vocational)', ''),
(4, 'HSC', 'HSC'),
(4, 'A Level', ''),
(4, 'Alim (Madrasah)', ''),
(4, 'HSC (Vocational)', ''),
(4, 'HSC (BMT)', ''),
(5, 'Diploma of Higher Education', 'DipHE'),
(5, 'Postgraduate Diploma', 'PGD'),
(5, 'Diploma in Computer Science', 'Dip.C.S.'),
(5, 'Diploma in Business Administration', 'Dip.B.A.'),
(5, 'Diploma in Engineering', ''),
(5, 'Diploma in Medical Technology', ''),
(5, 'Diploma in Nursing', ''),
(5, 'Diploma in Commerce', ''),
(5, 'Diploma in Business Studies', ''),
(5, 'Diploma in Pathology', ''),
(5, 'Diploma (Vocational)', ''),
(5, 'Diploma in Hotel Management', ''),
(5, 'Diploma in Mechanical', ''),
(5, 'Diploma in Refrigeration and Air Conditioning', ''),
(5, 'Diploma in Electrical', ''),
(5, 'Diploma in Automobile', ''),
(5, 'Diploma in Power', ''),
(5, 'Diploma in Electronics', ''),
(5, 'Diploma in Architecture', ''),
(5, 'Diploma in Electro Medical', ''),
(5, 'Diploma in Civil', ''),
(5, 'Diploma in Marine Engineering', ''),
(5, 'Diploma in Medical', ''),
(5, 'Diploma in Midwifery', ''),
(5, 'Diploma in Medical Ultrasound', ''),
(5, 'Diploma in Health Technology and Services', ''),
(5, 'Diploma in Agriculture', ''),
(5, 'Diploma in Fisheries', ''),
(5, 'Diploma in Livestock', ''),
(5, 'Diploma in Forestry', ''),
(5, 'Diploma in Textile Engineering', ''),
(5, 'Certificate in Marine Trade', ''),
(6, 'Bachelor of Arts', 'BA'),
(6, 'Bachelor of Science', 'BS'),
(6, 'Bachelor of Engineering', 'B.Eng.'),
(6, 'Bachelor of Commerce', 'BCom'),
(6, 'Bachelor of Dental Surgery (BDS)', 'BDS'),
(6, 'Bachelor of Education', 'B.Ed.'),
(6, 'Bachelor of Physical Education (B.P.Ed)', 'B.P.Ed'),
(6, 'Bachelor of Technology', 'B.Tech.'),
(6, 'Bachelor of Nursing', 'B.N.'),
(6, 'Bachelor of Business Administration', 'BBA'),
(6, 'Bachelor of Business Studies (BBS)', 'BBS'),
(6, 'Bachelor of Fine Arts', 'B.F.A'),
(6, 'Bachelor of Computer Science', 'BSC'),
(6, 'Bachelor of Public Administration', 'B.P.A.'),
(6, 'Bachelor of Social Work', 'B.S.W.'),
(6, 'Bachelor of Social Science (BSS)', 'BSS'),
(6, 'Bachelor of Accountancy', 'BAcc'),
(6, 'Bachelor of Architecture', 'B.Arch'),
(6, 'Bachelor of Computer Application', 'BCA'),
(6, 'Bachelor of Civil Law', 'BCL'),
(6, 'Bachelor of Divinity', 'BDiv'),
(6, 'Bachelor of Economics', 'BEc'),
(6, 'Bachelor of Law', 'LLB'),
(6, 'Bachelor of Letters', 'BLitt'),
(6, 'Bachelor of Music', 'BM'),
(6, 'Bachelor of Management Studies', 'BMS'),
(6, 'Bachelor of Pharmacy', 'B.Pharm'),
(6, 'Bachelor of Philosophy', 'BPhil'),
(6, 'Bachelor of Science in Nursing', 'BSN'),
(6, 'Bachelor of Theology', 'BTh'),
(6, 'Bachelor of Medicine and Bachelor of Surgery', 'MBBS'),
(6, 'Fazil (Madrasah Pass)', ''),
(6, 'Doctor of Veterinary Medicine (DVM)', 'DVM'),
(6, 'Doctor of Arts', 'DA'),
(6, 'Doctor of Audiology', 'AuD'),
(6, 'Doctor of Canon Law', 'JCD'),
(6, 'Doctor of Civil Law', 'DCL'),
(6, 'Doctor of Clinical Psychology', 'DClinPsy'),
(6, 'Doctor of Divinity', 'DDiv'),
(6, 'Doctor of Letters', 'DLitt'),
(6, 'Doctor of Ministry', 'DMin'),
(6, 'Doctor of Naturopathic Medicine', 'ND'),
(6, 'Doctor of Science', 'DSc or ScD'),
(6, 'Doctor of Theology', 'ThD'),
(6, 'Doctor of Dental Medicine', 'D.M.D.'),
(6, 'Doctor of Business Administration', 'D.B.A.'),
(6, 'Doctor of Social Science', 'D.Soc.Sc.'),
(6, 'Doctor of Chiropractic', 'D.C.'),
(6, 'Doctor of Osteopathic Medicine', 'D.O.'),
(6, 'Doctor of Psychology', 'Psy.D.'),
(6, 'Doctor of Musical Arts', 'DMA'),
(6, 'Doctor of Philosophy', 'Ph.D.'),
(6, 'Doctor of Medicine', 'M.D.'),
(6, 'Doctor of Dental Surgery', 'D.D.S.'),
(6, 'Doctor of Pharmacy', 'Pharm.D.'),
(6, 'Doctor of Education', 'Ed.D.'),
(6, 'Doctor of Engineering', 'Eng.D.'),
(6, 'Doctor of Juridical Science', 'S.J.D.'),
(6, 'Doctor of Nursing Practice', 'D.N.P.'),
(6, 'Doctor of Optometry', 'O.D.'),
(6, 'Doctor of Physical Therapy', 'D.P.T.'),
(6, 'Juris Doctor', 'J.D.'),
(6, 'Magister Juris', 'MJur'),
(6, 'Licentiate in Sacred Theology', 'STL'),
(7, 'Master of Arts', 'MA'),
(7, 'Master of Science', 'M.S.'),
(7, 'Master of Architecture (M.Arch)', 'M.Arch'),
(7, 'Master of Pharmacy (M.Pharm)', 'M.Pharm'),
(7, 'Master of Fine Arts', 'M.F.A.'),
(7, 'Master of Engineering', 'M.Eng.'),
(7, 'Master of Law', 'LLM'),
(7, 'Master of Commerce', 'MCom'),
(7, 'Master of Education', 'M.Ed'),
(7, 'Master of Technology', 'M.Tech.'),
(7, 'Master of Public Health', 'M.P.H.'),
(7, 'Master of Social Work', 'M.S.W.'),
(7, 'Master of Social Science (MSS)', 'MSS'),
(7, 'Master of Information Technology', 'M.I.T.'),
(7, 'Master of Business Studies (MBS)', 'MBS'),
(7, 'Master of Business Administration', 'MBA'),
(7, 'Master of Business Management (MBM)', 'MBM'),
(7, 'Master of Development Studies (MDS)', 'MDS'),
(7, 'Master of Computer Science', 'MSc'),
(7, 'Master of Counselling', 'MCouns'),
(7, 'Master of Divinity', 'MDiv'),
(7, 'Master of Letters', 'MLitt'),
(7, 'Master of Medicine', 'MMed'),
(7, 'Master of Management Studies', 'MMS'),
(7, 'Master of Philosophy (M.Phil)', 'M.Phil'),
(7, 'Master of Public Administration', 'MPA'),
(7, 'Master of Research', 'MRes'),
(7, 'Master of Sacred Theology', 'STM'),
(7, 'Master of Science in Nursing', 'MSN'),
(7, 'Master of Studies', 'MSt'),
(7, 'Master of Surgery', 'ChM or MS'),
(7, 'Masters in Computer Application (MCA)', 'MCA'),
(7, 'Executive Master of Business Administration (EMBA)', 'EMBA'),
(7, 'Fellowship of the College of Physicians and Surgeons (FCPS)', 'FCPS'),
(7, 'Kamil (Madrasah)', ''),
(7, 'Masters in Bank Management (MBM)', 'MBM'),
(7, 'Masters in Information Systems Security (MISS)', 'MISS'),
(7, 'Master of Information & Communication Technology (MICT)', 'MICT'),
(8, 'Associate of Applied Science', 'AAS'),
(8, 'Associate of Arts', 'A.A.'),
(8, 'Associate of Science', 'A.S.'),
(8, 'Associate of Business Administration', 'A.B.A.'),
(8, 'Associate of Engineering', 'A.Eng.'),
(8, 'Associate of Applied Arts', 'A.A.A.'),
(8, 'Associate of Fine Arts', 'A.F.A.'),
(8, 'Associate of Nursing', 'A.N.');
