INSERT INTO education_levels (`level_name`) VALUES
('PSC/5 pass'),
('JSC/JDC/8 pass'),
('Secondary'),
('Higher Secondary'),
('Diploma'),
('Bachelor'),
('Master'),
('Associate Degree'),
('Ph.D.'),
('Professional Certification');

-- ('Technical Degree'),
-- ('Undergraduate Certificate'),
-- ('Advanced Diploma'),
-- ('Executive Education'),
-- ('Specialist Degree'),
-- ('Licentiate Degree'),
-- ('Foundation Degree'),
-- ('General Educational Development (GED)'),
-- ('National Vocational Qualification (NVQ)'),
-- ('City & Guilds Certification'),
-- ('Apprenticeship Program'),
-- ('General Certificate of Secondary Education (GCSE)'),
-- ('Cambridge Pre-U'),
-- ('SAT Subject Test'),
-- ('European Baccalaureate (EB)'),
-- ('Advanced Placement (AP)'),
-- ('International General Certificate of Secondary Education (IGCSE)'),
-- ('Higher National Certificate (HNC)'),
-- ('Higher National Diploma (HND)'),
-- ('Pre-University Certificate'),
-- ('Certificate of Higher Education'),
-- ('Open University Certificate');
