INSERT INTO education_subjects (`education_level_id`, `subject_name`, `degree_level`) VALUES
(3, 'Science', 'Secondary'),
(3, 'Arts', 'Secondary'),
(3, 'Commerce', 'Secondary'),
(4, 'Science', 'Higher Secondary'),
(4, 'Arts', 'Higher Secondary'),
(4, 'Commerce', 'Higher Secondary'),
(6, 'Computer Science', 'Bachelor'),
(6, 'Electrical Engineering', 'Bachelor'),
(6, 'English Literature', 'Bachelor'),
(6, 'Business Administration', 'Bachelor'),
(6, 'Environmental Science', 'Bachelor'),
(6, 'Psychology', 'Bachelor'),
(6, 'Mechanical Engineering', 'Bachelor'),
(6, 'Political Science', 'Bachelor'),
(6, 'Economics', 'Bachelor'),
(6, 'Mathematics', 'Bachelor'),
(6, 'History', 'Bachelor'),
(6, 'Chemistry', 'Bachelor'),
(6, 'Physics', 'Bachelor'),
(6, 'Marketing', 'Bachelor'),
(6, 'Biology', 'Bachelor'),
(6, 'Sociology', 'Bachelor'),
(6, 'Civil Engineering', 'Bachelor'),
(6, 'Communication Studies', 'Bachelor'),
(6, 'Finance', 'Bachelor'),
(6, 'Human Resource Management', 'Bachelor'),
(6, 'Fine Arts', 'Bachelor'),
(6, 'Music', 'Bachelor'),
(6, 'Nursing', 'Bachelor'),
(6, 'Education', 'Bachelor'),
(6, 'Accounting', 'Bachelor'),
(6, 'Graphic Design', 'Bachelor'),
(6, 'International Relations', 'Bachelor'),
(6, 'Architecture', 'Bachelor'),
(6, 'Information Technology', 'Bachelor'),
(6, 'Artificial Intelligence', 'Bachelor'),
(6, 'Digital Marketing', 'Bachelor'),
(6, 'Public Health', 'Bachelor'),
(6, 'Philosophy', 'Bachelor'),
(6, 'Criminal Justice', 'Bachelor'),
(6, 'Nutrition and Dietetics', 'Bachelor'),
(6, 'Film Studies', 'Bachelor'),
(6, 'Mechatronics Engineering', 'Bachelor'),
(6, 'Biotechnology', 'Bachelor'),
(6, 'Journalism', 'Bachelor'),
(6, 'Dental Hygiene', 'Bachelor'),
(6, 'Geology', 'Bachelor'),
(6, 'Music Composition', 'Bachelor'),
(6, 'Mathematical Economics', 'Bachelor'),
(6, 'Fashion Design', 'Bachelor'),
(6, 'Astronomy', 'Bachelor'),
(6, 'Industrial Engineering', 'Bachelor'),
(6, 'Environmental Engineering', 'Bachelor'),
(6, 'Hospitality Management', 'Bachelor'),
(6, 'Sports Science', 'Bachelor'),
(6, 'Marketing Communications', 'Bachelor'),
(6, 'Drama and Theater Arts', 'Bachelor'),
(6, 'Applied Mathematics', 'Bachelor'),
(6, 'Human Biology', 'Bachelor'),
(6, 'Healthcare Management', 'Bachelor'),
(6, 'Biochemistry', 'Bachelor'),
(6, 'Data Science', 'Bachelor'),
(6, 'Public Relations', 'Bachelor'),
(6, 'Animation', 'Bachelor'),
(6, 'Materials Science', 'Bachelor'),
(6, 'International Business', 'Bachelor'),
(6, 'Forensic Science', 'Bachelor'),
(6, 'Robotics', 'Bachelor'),
(6, 'Astrophysics', 'Bachelor'),
(6, 'Philology', 'Bachelor'),
(6, 'Biomedical Engineering', 'Bachelor'),
(6, 'Environmental Studies', 'Bachelor'),
(6, 'Cognitive Science', 'Bachelor'),
(6, 'Graphic Communication', 'Bachelor'),
(6, 'Political Economy', 'Bachelor'),
(6, 'Urban Planning', 'Bachelor'),
(6, 'Supply Chain Management', 'Bachelor'),
(6, 'Aviation Management', 'Bachelor'),
(6, 'Game Design', 'Bachelor'),
(6, 'Neuroscience', 'Bachelor'),
(6, 'Humanities', 'Bachelor'),
(6, 'Chemical Engineering', 'Bachelor'),
(6, 'Geography', 'Bachelor'),
(6, 'Digital Media', 'Bachelor'),
(6, 'Interior Design', 'Bachelor'),
(6, 'Industrial Design', 'Bachelor'),
(6, 'Renewable Energy Engineering', 'Bachelor'),
(6, 'Statistics', 'Bachelor'),
(6, 'Actuarial Science', 'Bachelor'),
(6, 'International Law', 'Bachelor'),
(6, 'Social Work', 'Bachelor'),
(6, 'Philosophy of Science', 'Bachelor'),
(6, 'Quantitative Finance', 'Bachelor'),
(6, 'Global Studies', 'Bachelor'),
(6, 'Criminology', 'Bachelor'),
(7, 'Computer Science', 'Master'),
(7, 'Mechanical Engineering', 'Master'),
(7, 'Electrical Engineering', 'Master'),
(7, 'Civil Engineering', 'Master'),
(7, 'Biology', 'Master'),
(7, 'Chemistry', 'Master'),
(7, 'Physics', 'Master'),
(7, 'Mathematics', 'Master'),
(7, 'Business Administration', 'Master'),
(7, 'Economics', 'Master'),
(7, 'Psychology', 'Master'),
(7, 'Sociology', 'Master'),
(7, 'History', 'Master'),
(7, 'Political Science', 'Master'),
(7, 'English Literature', 'Master'),
(7, 'Communication Studies', 'Master'),
(7, 'Fine Arts', 'Master'),
(7, 'Music', 'Master'),
(7, 'Nursing', 'Master'),
(7, 'Education', 'Master'),
(7, 'Environmental Science', 'Master'),
(7, 'Data Science', 'Master'),
(7, 'Electronics and Communication Engineering', 'Master'),
(7, 'Literature and Creative Writing', 'Master'),
(7, 'Executive MBA', 'Master'),
(7, 'Environmental Management', 'Master'),
(7, 'Clinical Psychology', 'Master'),
(7, 'Mechanical Design Engineering', 'Master'),
(7, 'International Relations', 'Master'),
(7, 'Applied Economics', 'Master'),
(7, 'Mathematical Modeling', 'Master'),
(7, 'Modern History', 'Master'),
(7, 'Chemical Engineering', 'Master'),
(7, 'Theoretical Physics', 'Master'),
(7, 'Digital Marketing', 'Master'),
(7, 'Genetic Engineering', 'Master'),
(7, 'Social Work', 'Master'),
(7, 'Structural Engineering', 'Master'),
(7, 'Media and Public Relations', 'Master'),
(7, 'Corporate Finance', 'Master'),
(7, 'Organizational Development', 'Master'),
(7, 'Computer Science Research', 'Master'),
(7, 'Business Strategy', 'Master'),
(7, 'Advanced Mechanical Engineering', 'Master'),
(7, 'English Literature Studies', 'Master'),
(7, 'Environmental Science Research', 'Master'),
(7, 'Public Policy and Administration', 'Master'),
(7, 'Historical Research', 'Master'),
(7, 'Advanced Mathematics', 'Master'),
(7, 'Advanced Chemistry Studies', 'Master'),
(7, 'Strategic Marketing', 'Master'),
(7, 'Communication Research', 'Master'),
(7, 'Advanced Biology Research', 'Master'),
(7, 'Sociological Studies', 'Master'),
(7, 'Advanced Accounting Practices', 'Master'),
(7, 'Education Leadership', 'Master'),
(7, 'Advanced Graphic Design', 'Master'),
(7, 'Global Affairs', 'Master'),
(7, 'Advanced Nursing Practices', 'Master'),
(7, 'Electrical System Optimization', 'Master'),
(7, 'Architectural Design and Research', 'Master'),
(7, 'Advanced Information Technology', 'Master'),
(7, 'Artificial Intelligence Research', 'Master'),
(7, 'Digital Marketing Strategies', 'Master'),
(7, 'Human Resource Development', 'Master'),
(7, 'Global Public Health', 'Master'),
(7, 'Philosophical Studies', 'Master'),
(7, 'Criminal Justice Administration', 'Master'),
(7, 'Advanced Nutrition Sciences', 'Master'),
(7, 'Film Production and Analysis', 'Master'),
(7, 'Mechatronics Engineering Research', 'Master'),
(7, 'Biomedical Research', 'Master'),
(7, 'Journalism and Media Studies', 'Master'),
(7, 'Advanced Dental Practices', 'Master'),
(7, 'Geological Research', 'Master'),
(7, 'Music Composition and Theory', 'Master'),
(7, 'Mathematical Economics Research', 'Master'),
(7, 'Fashion Design and Innovation', 'Master'),
(7, 'Astrophysical Research', 'Master'),
(7, 'Industrial Engineering Management', 'Master'),
(7, 'Environmental Engineering Research', 'Master'),
(7, 'Hospitality Management Strategies', 'Master'),
(7, 'Advanced Sports Science Research', 'Master'),
(7, 'Integrated Marketing Communications', 'Master'),
(7, 'Drama and Theater Arts Research', 'Master'),
(7, 'Applied Mathematics Studies', 'Master'),
(7, 'Advanced Human Biology Research', 'Master'),
(7, 'Healthcare Management and Leadership', 'Master'),
(7, 'Biochemical Research', 'Master'),
(7, 'Advanced Data Science', 'Master'),
(7, 'Public Relations Strategies', 'Master'),
(7, 'Animation and Multimedia Studies', 'Master'),
(7, 'Advanced Materials Science', 'Master'),
(7, 'Global Business Management', 'Master'),
(7, 'Forensic Science Research', 'Master'),
(7, 'Robotics and Automation', 'Master'),
(7, 'Astrophysics Research', 'Master'),
(7, 'Philological Studies', 'Master'),
(7, 'Biomedical Engineering Research', 'Master'),
(7, 'Environmental Studies Research', 'Master'),
(7, 'Cognitive Science Research', 'Master'),
(7, 'Graphic Communication Strategies', 'Master'),
(7, 'Political Economy Research', 'Master'),
(7, 'Urban Planning and Design', 'Master'),
(7, 'Supply Chain Management Strategies', 'Master'),
(7, 'Aviation Management and Leadership', 'Master'),
(7, 'Game Design and Development', 'Master'),
(7, 'Neuroscience Research', 'Master'),
(7, 'Humanities Research', 'Master'),
(7, 'Chemical Engineering Research', 'Master'),
(7, 'Geographical Research', 'Master'),
(7, 'Digital Media Strategies', 'Master'),
(7, 'Interior Design and Innovation', 'Master'),
(7, 'Industrial Design Research', 'Master'),
(7, 'Renewable Energy Engineering', 'Master'),
(7, 'Advanced Statistics', 'Master'),
(7, 'Actuarial Science Research', 'Master'),
(7, 'International Law Studies', 'Master'),
(7, 'Advanced Social Work', 'Master'),
(7, 'Philosophy of Science Research', 'Master'),
(7, 'Quantitative Finance Strategies', 'Master'),
(7, 'Global Studies Research', 'Master'),
(7, 'Criminology Research', 'Master');
