INSERT INTO employment_types (`employment_type`) VALUES
('Full-Time'),
('Part-Time'),
('Contract'),
('Temporary'),
('Freelance'),
('Internship'),
('Apprenticeship'),
('Remote'),
('Hybrid'),
('On-Site'),
('Work from Home'),
('Flexitime'),
('Job Share'),
('Seasonal'),
('Volunteer'),
('Commission-Based'),
('Consultant'),
('Temporary-to-Hire'),
('Per Diem'),
('Project-Based'),
('Freelance/Contract to Hire'),
('Self-Employed'),
('Traineeship'),
('Cooperative Education'),
('Fixed-Term'),
('Zero Hours'),
('Casual'),
('Zero Contract Hours'),
('Outsourcing'),
('Secondment'),
('Remote-First'),
('Permanent'),
('Flexplace'),
('Job Rotation'),
('Job Redesign'),
('Telecommuting'),
('Shift-Based'),
('Hot Desk'),
('Compressed Workweek'),
('Annualized Hours'),
('Zero-Hours Contract'),
('Daily Contract'),
('Substitute'),
('Expat'),
('Freelance/Remote'),
('Zero-Hour Part-Time'),
('Virtual'),
('Gig Economy'),
('Voluntary Part-Time'),
('Regular/Permanent'),
('Permanently Temporary'),
('Full-time - Remote'),
('Full-time - Hybrid'),
('Full-time - Work from Office'),
('Part-time - Remote'),
('Part-time - Hybrid'),
('Part-time - Work from Office'),
('Contract - Remote'),
('Contract - Hybrid'),
('Contract - Work from Office'),
('Internship - Remote'),
('Internship - Hybrid'),
('Internship - Work from Office'),
('Temporary - Remote'),
('Temporary - Hybrid'),
('Temporary - Work from Office'),
('Freelance - Remote'),
('Freelance - Hybrid'),
('Freelance - Work from Office'),
('Consultant - Remote'),
('Consultant - Hybrid'),
('Consultant - Work from Office'),
('Work from Office'),
('Co-op'),
('Flexible'),
('Zero-Hour Contract'),
('On-Call'),
('Flextime'),
('Remote-first'),
('Freelance/Contractor'),
('Remote-First, Headquarters'),
('Remote-First, Regional Office'),
('Remote-First, Local Office'),
('Remote-First, Global Team'),
('Remote-First, Global Company'),
('Flexible Hours'),
('Open Schedule'),
('Results-Only Work Environment (ROWE)'),
('Hot Desking'),
('Activity-Based Working'),
('Sabbatical'),
('Full-Time Equivalent (FTE)'),
('Stipend-Based'),
('Commission-Only'),
('Piece Rate'),
('Hourly Rate'),
('Day Laborer');
