INSERT INTO experience_ranges (`experience`) VALUES
('N/A'),
('At least 1 years'),
('At least 2 years'),
('At least 3 years'),
('At least 4 years'),
('At least 5 years'),
('At most 1 years'),
('At most 2 years'),
('At most 3 years'),
('At most 4 years'),
('At most 5 years'),
('1+ years'),
('2+ years'),
('3+ years'),
('4+ years'),
('5+ years'),
('6+ years'),
('7+ years'),
('8+ years'),
('9+ years'),
('10+ years'),
('11+ years'),
('12+ years'),
('1 to 2 years'),
('1 to 3 years'),
('1 to 4 years'),
('2 to 3 years'),
('2 to 4 years'),
('2 to 5 years'),
('3 to 4 years'),
('3 to 5 years'),
('3 to 6 years'),
('4 to 5 years'),
('4 to 6 years'),
('4 to 7 years'),
('5 to 6 years'),
('5 to 7 years'),
('5 to 8 years'),
('6 to 7 years'),
('6 to 8 years'),
('6 to 9 years'),
('7 to 8 years'),
('7 to 9 years'),
('7 to 10 years'),
('8 to 10 years'),
('9 to 12 years'),
('10 to 12 years');
