INSERT INTO genders (`gender_name`) VALUES
('Male'),
('Female'),
('Non-Binary'),
('Agender'),
('Bigender'),
('Genderqueer'),
('Genderfluid'),
('Androgynous'),
('Two-Spirit'),
('Demiboy'),
('Demigirl'),
('Bi-Gender'),
('Transgender'),
('Cisgender'),
('Other'),
('Prefer not to say'),
('Not Applicable'),
('Man'),
('Woman'),
('Trans Man'),
('Trans Woman'),
('Gender Nonconforming'),
('Gender Questioning'),
('Fluid'),
('Neutrois'),
('Pangender'),
('Third Gender'),
('Two-Gender'),
('Transmasculine'),
('Transfeminine'),
('Third Sex'),
('Hijra'),
('Kathoey'),
('X-gender'),
('Y-gender'),
('Z-gender'),
('Other/Specify'),
('Prefer to self-describe'),
('Not Stated'),
('Unknown'),
('Decline to State'),
('Other Gender Identity'),
('Prefer to Identify'),
('Prefer to Specify'),
('Prefer Not To Say'),
('Not Disclosed'),
('No Gender');
