INSERT INTO `industries` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Accounting', 0, NULL, NULL),
(2, 'Airlines / Aviation', 0, NULL, NULL),
(3, 'Alternative Dispute Resolution', 0, NULL, NULL),
(4, 'Alternative Medicine', 0, NULL, NULL),
(5, 'Animation', 0, NULL, NULL),
(6, 'Apparel / Fashion', 0, NULL, NULL),
(7, 'Architecture / Planning', 0, NULL, NULL),
(8, 'Arts / Crafts', 0, NULL, NULL),
(9, 'Automotive', 0, NULL, NULL),
(10, 'Aviation / Aerospace', 0, NULL, NULL),
(11, 'Banking / Mortgage', 0, NULL, NULL),
(12, 'Biotechnology / Greentech', 0, NULL, NULL),
(13, 'Broadcast Media', 0, NULL, NULL),
(14, 'Building Materials', 0, NULL, NULL),
(15, 'Business Supplies / Equipment', 0, NULL, NULL),
(16, 'Capital Markets / Hedge Fund / Private Equity', 0, NULL, NULL),
(17, 'Chemicals', 0, NULL, NULL),
(18, 'Civic / Social Organization', 0, NULL, NULL),
(19, 'Civil Engineering', 0, NULL, NULL),
(20, 'Commercial Real Estate', 0, NULL, NULL),
(21, 'Computer Games', 0, NULL, NULL),
(22, 'Computer Hardware', 0, NULL, NULL),
(23, 'Computer Networking', 0, NULL, NULL),
(24, 'Computer Software / Engineering', 0, NULL, NULL),
(25, 'Computer / Network Security', 0, NULL, NULL),
(26, 'Construction', 0, NULL, NULL),
(27, 'Consumer Electronics', 0, NULL, NULL),
(28, 'Consumer Goods', 0, NULL, NULL),
(29, 'Consumer Services', 0, NULL, NULL),
(30, 'Cosmetics', 0, NULL, NULL),
(31, 'Dairy', 0, NULL, NULL),
(32, 'Defense / Space', 0, NULL, NULL),
(33, 'Design', 0, NULL, NULL),
(34, 'E-Learning', 0, NULL, NULL),
(35, 'Education Management', 0, NULL, NULL),
(36, 'Electrical / Electronic Manufacturing', 0, NULL, NULL),
(37, 'Entertainment / Movie Production', 0, NULL, NULL),
(38, 'Environmental Services', 0, NULL, NULL),
(39, 'Events Services', 0, NULL, NULL),
(40, 'Executive Office', 0, NULL, NULL),
(41, 'Facilities Services', 0, NULL, NULL),
(42, 'Farming', 0, NULL, NULL),
(43, 'Financial Services', 0, NULL, NULL),
(44, 'Fine Art', 0, NULL, NULL),
(45, 'Fishery', 0, NULL, NULL),
(46, 'Food Production', 0, NULL, NULL),
(47, 'Food / Beverages', 0, NULL, NULL),
(48, 'Fundraising', 0, NULL, NULL),
(49, 'Furniture', 0, NULL, NULL),
(50, 'Gambling / Casinos', 0, NULL, NULL),
(51, 'Glass / Ceramics / Concrete', 0, NULL, NULL),
(52, 'Government Administration', 0, NULL, NULL),
(53, 'Government Relations', 0, NULL, NULL),
(54, 'Graphic Design / Web Design', 0, NULL, NULL),
(55, 'Health / Fitness', 0, NULL, NULL),
(56, 'Higher Education / Acadamia', 0, NULL, NULL),
(57, 'Hospital / Health Care', 0, NULL, NULL),
(58, 'Hospitality', 0, NULL, NULL),
(59, 'Human Resources / HR', 0, NULL, NULL),
(60, 'Import / Export', 0, NULL, NULL),
(61, 'Individual / Family Services', 0, NULL, NULL),
(62, 'Industrial Automation', 0, NULL, NULL),
(63, 'Information Services', 0, NULL, NULL),
(64, 'Information Technology / IT', 0, NULL, NULL),
(65, 'Insurance', 0, NULL, NULL),
(66, 'International Affairs', 0, NULL, NULL),
(67, 'International Trade / Development', 0, NULL, NULL),
(68, 'Internet', 0, NULL, NULL),
(69, 'Investment Banking / Venture', 0, NULL, NULL),
(70, 'Investment Management / Hedge Fund / Private Equity', 0, NULL, NULL),
(71, 'Judiciary', 0, NULL, NULL),
(72, 'Law Enforcement', 0, NULL, NULL),
(73, 'Law Practice / Law Firms', 0, NULL, NULL),
(74, 'Legal Services', 0, NULL, NULL),
(75, 'Legislative Office', 0, NULL, NULL),
(76, 'Leisure / Travel', 0, NULL, NULL),
(77, 'Library', 0, NULL, NULL),
(78, 'Logistics / Procurement', 0, NULL, NULL),
(79, 'Luxury Goods / Jewelry', 0, NULL, NULL),
(80, 'Machinery', 0, NULL, NULL),
(81, 'Management Consulting', 0, NULL, NULL),
(82, 'Maritime', 0, NULL, NULL),
(83, 'Market Research', 0, NULL, NULL),
(84, 'Marketing / Advertising / Sales', 0, NULL, NULL),
(85, 'Mechanical or Industrial Engineering', 0, NULL, NULL),
(86, 'Media Production', 0, NULL, NULL),
(87, 'Medical Equipment', 0, NULL, NULL),
(88, 'Medical Practice', 0, NULL, NULL),
(89, 'Mental Health Care', 0, NULL, NULL),
(90, 'Military Industry', 0, NULL, NULL),
(91, 'Mining / Metals', 0, NULL, NULL),
(92, 'Motion Pictures / Film', 0, NULL, NULL),
(93, 'Museums / Institutions', 0, NULL, NULL),
(94, 'Music', 0, NULL, NULL),
(95, 'Nanotechnology', 0, NULL, NULL),
(96, 'Newspapers / Journalism', 0, NULL, NULL),
(97, 'Non-Profit / Volunteering', 0, NULL, NULL),
(98, 'Oil / Energy / Solar / Greentech', 0, NULL, NULL),
(99, 'Online Publishing', 0, NULL, NULL),
(100, 'Other Industry', 0, NULL, NULL),
(101, 'Outsourcing / Offshoring', 0, NULL, NULL),
(102, 'Package / Freight Delivery', 0, NULL, NULL),
(103, 'Packaging / Containers', 0, NULL, NULL),
(104, 'Paper / Forest Products', 0, NULL, NULL),
(105, 'Performing Arts', 0, NULL, NULL),
(106, 'Pharmaceuticals', 0, NULL, NULL),
(107, 'Philanthropy', 0, NULL, NULL),
(108, 'Photography', 0, NULL, NULL),
(109, 'Plastics', 0, NULL, NULL),
(110, 'Political Organization', 0, NULL, NULL),
(111, 'Primary / Secondary Education', 0, NULL, NULL),
(112, 'Printing', 0, NULL, NULL),
(113, 'Professional Training', 0, NULL, NULL),
(114, 'Program Development', 0, NULL, NULL),
(115, 'Public Relations / PR', 0, NULL, NULL),
(116, 'Public Safety', 0, NULL, NULL),
(117, 'Publishing Industry', 0, NULL, NULL),
(118, 'Railroad Manufacture', 0, NULL, NULL),
(119, 'Ranching', 0, NULL, NULL),
(120, 'Real Estate / Mortgage', 0, NULL, NULL),
(121, 'Recreational Facilities / Services', 0, NULL, NULL),
(122, 'Religious Institutions', 0, NULL, NULL),
(123, 'Renewables / Environment', 0, NULL, NULL),
(124, 'Research Industry', 0, NULL, NULL),
(125, 'Restaurants', 0, NULL, NULL),
(126, 'Retail Industry', 0, NULL, NULL),
(127, 'Security / Investigations', 0, NULL, NULL),
(128, 'Semiconductors', 0, NULL, NULL),
(129, 'Shipbuilding', 0, NULL, NULL),
(130, 'Sporting Goods', 0, NULL, NULL),
(131, 'Sports', 0, NULL, NULL),
(132, 'Staffing / Recruiting', 0, NULL, NULL),
(133, 'Supermarkets', 0, NULL, NULL),
(134, 'Telecommunications', 0, NULL, NULL),
(135, 'Textiles', 0, NULL, NULL),
(136, 'Think Tanks', 0, NULL, NULL),
(137, 'Tobacco', 0, NULL, NULL),
(138, 'Translation / Localization', 0, NULL, NULL),
(139, 'Transportation', 0, NULL, NULL),
(140, 'Utilities', 0, NULL, NULL),
(141, 'Venture Capital / VC', 0, NULL, NULL),
(142, 'Veterinary', 0, NULL, NULL),
(143, 'Warehousing', 0, NULL, NULL),
(144, 'Wholesale', 0, NULL, NULL),
(145, 'Wine / Spirits', 0, NULL, NULL),
(146, 'Wireless', 0, NULL, NULL),
(147, 'Writing / Editing', 0, NULL, NULL);
