INSERT INTO job_natures (`nature`) VALUES
('Full-Time'),
('Part-Time'),
('Contract'),
('Temporary'),
('Freelance'),
('Internship'),
('Apprenticeship'),
('Flexitime'),
('Seasonal'),
('Volunteer'),
('Commission-Based'),
('Project-Based'),
('Self-Employed'),
('Traineeship'),
('Fixed-Term'),
('Outsourcing'),
('Permanent'),
('Shift-Based'),
('Daily Contract'),
('Substitute'),
('Virtual'),
('Voluntary Part-Time'),
('Hourly Rate'),
('Day Laborer');
