INSERT INTO job_places (`workplace`) VALUES
('Remote'),
('Hybrid'),
('On-Site'),
('Work from Home'),
('Work from Office'),
('Remote-First'),
('Virtual'),
('Full-time - Remote'),
('Full-time - Hybrid'),
('Full-time - Work from Office'),
('Part-time - Remote'),
('Part-time - Hybrid'),
('Part-time - Work from Office'),
('Contract - Remote'),
('Contract - Hybrid'),
('Contract - Work from Office'),
('Internship - Remote'),
('Internship - Hybrid'),
('Internship - Work from Office'),
('Temporary - Remote'),
('Temporary - Hybrid'),
('Temporary - Work from Office');
