INSERT INTO languages (`language_name`, `native_name`) VALUES ("Afar", "Afaraf");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Abkhaz", "аҧсуа бызшәа, аҧсшәа");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Avestan", "avesta");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Afrikaans", "Afrikaans");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Akan", "Akan");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Amharic", "አማርኛ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Aragonese", "aragonés");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Arabic", "العربية");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Assamese", "অসমীয়া");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Avaric", "авар мацӀ, магӀарул мацӀ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Aymara", "aymar aru");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Azerbaijani", "azərbaycan dili");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("South Azerbaijani", "تورکجه");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bashkir", "башҡорт теле");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Belarusian", "беларуская мова");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bulgarian", "български език");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bihari", "भोजपुरी");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bislama", "Bislama");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bambara", "bamanankan");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bangla", "বাংলা");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tibetan", "བོད་ཡིག");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Breton", "brezhoneg");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Bosnian", "bosanski jezik");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Valencian", "català, valencià");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Chechen", "нохчийн мотт");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Chamorro", "Chamoru");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Corsican", "corsu, lingua corsa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Cree", "ᓀᐦᐃᔭᐍᐏᐣ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Czech", "čeština, český jazyk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Slavonic", "ѩзыкъ словѣньскъ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Chuvash", "чӑваш чӗлхи");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Welsh", "Cymraeg");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Danish", "dansk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("German", "Deutsch");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Maldivian", "ދިވެހި");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Dzongkha", "རྫོང་ཁ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ewe", "Eʋegbe");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Greek", "ελληνικά");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("English", "English");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Esperanto", "Esperanto");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Spanish", "español, castellano");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Estonian", "eesti, eesti keel");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Basque", "euskara, euskera");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Persian (Farsi)", "فارسی");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Fula", "Fulfulde, Pulaar, Pular");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Finnish", "suomi, suomen kieli");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Fijian", "vosa Vakaviti");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Faroese", "føroyskt");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("French", "français, langue française");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Western Frisian", "Frysk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Irish", "Gaeilge");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Scottish Gaelic", "Gàidhlig");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Galician", "galego");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Guaraní", "Avañe'ẽ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Gujarati", "ગુજરાતી");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Manx", "Gaelg, Gailck");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Hausa", "Hausa, هَوُسَ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Hebrew (modern)", "עברית");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Hindi", "हिन्दी, हिंदी");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Hiri Motu", "Hiri Motu");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Croatian", "hrvatski jezik");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Haitian", "Kreyòl ayisyen");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Hungarian", "magyar");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Armenian", "Հայերեն");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Herero", "Otjiherero");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Interlingua", "Interlingua");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Indonesian", "Bahasa Indonesia");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Interlingue", "Originally called Occidental; then Interlingue after WWII");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Igbo", "Asụsụ Igbo");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Nuosu", "ꆈꌠ꒿ Nuosuhxop");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Inupiaq", "Iñupiaq, Iñupiatun");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ido", "Ido");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Icelandic", "Íslenska");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Italian", "italiano");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Inuktitut", "ᐃᓄᒃᑎᑐᑦ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Japanese", "日本語 (にほんご)");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Javanese", "basa Jawa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Georgian", "ქართული");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kongo", "KiKongo");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kikuyu, Gikuyu", "Gĩkũyũ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kwanyama, Kuanyama", "Kuanyama");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kazakh", "қазақ тілі");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kalaallisut, Greenlandic", "kalaallisut, kalaallit oqaasii");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Khmer", "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kannada", "ಕನ್ನಡ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Korean", "한국어 (韓國語), 조선어 (朝鮮語)");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kanuri", "Kanuri");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kashmiri", "कश्मीरी, كشميري");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kurdish", "Kurdî, كوردی");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Komi", "коми кыв");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Cornish", "Kernewek");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kyrgyz", "Кыргызча, Кыргыз тили");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Latin", "latine, lingua latina");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Luxembourgish", "Lëtzebuergesch");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ganda", "Luganda");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Limburgish", "Limburgs");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Lingala", "Lingála");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Lao", "ພາສາລາວ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Lithuanian", "lietuvių kalba");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Luba-Katanga", "Tshiluba");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Latvian", "latviešu valoda");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Malagasy", "fiteny malagasy");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Marshallese", "Kajin M̧ajeļ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Māori", "te reo Māori");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Macedonian", "македонски јазик");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Malayalam", "മലയാളം");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Mongolian", "монгол");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Marathi (Marāṭhī)", "मराठी");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Malay", "bahasa Melayu, بهاس ملايو");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Maltese", "Malti");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Burmese", "ဗမာစာ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Nauru", "Ekakairũ Naoero");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Norwegian Bokmål", "Norsk bokmål");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("North Ndebele", "isiNdebele");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Nepali", "नेपाली");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ndonga", "Owambo");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Dutch", "Nederlands, Vlaams");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Norwegian Nynorsk", "Norsk nynorsk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Norwegian", "Norsk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("South Ndebele", "isiNdebele");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Navajo, Navaho", "Diné bizaad, Dinékʼehǰí");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Chichewa", "chiCheŵa, chinyanja");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Occitan", "occitan, lenga d'òc");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ojibwe, Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Oromo", "Afaan Oromoo");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Oriya", "ଓଡ଼ିଆ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ossetian", "ирон æвзаг");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Panjabi", "ਪੰਜਾਬੀ, پنجابی");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Pāli", "पाऴि");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Polish", "język polski, polszczyzna");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Pashto, Pushto", "پښتو");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Portuguese", "português");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Quechua", "Runa Simi, Kichwa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Romansh", "rumantsch grischun");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kirundi", "Ikirundi");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Romanian", "limba română");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Russian", "русский язык");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Kinyarwanda", "Ikinyarwanda");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sanskrit (Saṁskṛta)", "संस्कृतम्");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sardinian", "sardu");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sindhi", "सिन्धी, سنڌي، سندھی");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Northern Sami", "Davvisámegiella");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sango", "yângâ tî sängö");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sinhala, Sinhalese", "සිංහල");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Slovak", "slovenčina, slovenský jazyk");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Slovene", "slovenski jezik, slovenščina");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Samoan", "gagana fa'a Samoa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Shona", "chiShona");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Somali", "Soomaaliga, af Soomaali");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Albanian", "gjuha shqipe");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Serbian", "српски језик");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Swati", "SiSwati");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Southern Sotho", "Sesotho");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Sundanese", "Basa Sunda");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Swedish", "Svenska");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Swahili", "Kiswahili");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tamil", "தமிழ்");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Telugu", "తెలుగు");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tajik", "тоҷикӣ, toğikī, تاجیکی");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Thai", "ไทย");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tigrinya", "ትግርኛ");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Turkmen", "Türkmen, Түркмен");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tagalog", "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tswana", "Setswana");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tonga (Tonga Islands)", "faka Tonga");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Turkish", "Türkçe");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tsonga", "Xitsonga");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tatar", "татар теле, tatar tele");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Twi", "Twi");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Tahitian", "Reo Tahiti");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Uyghur", "Uyƣurqə, ئۇيغۇرچە");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Ukrainian", "українська мова");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Urdu", "اردو");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Uzbek", "O‘zbek, Ўзбек, أۇزبېك");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Venda", "Tshivenḓa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Vietnamese", "Tiếng Việt");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Volapük", "Volapük");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Walloon", "walon");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Wolof", "Wollof");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Xhosa", "isiXhosa");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Yiddish", "ייִדיש");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Yoruba", "Yorùbá");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Zhuang", "Saɯ cueŋƅ, Saw cuengh");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Chinese", "中文 (Zhōngwén), 汉语, 漢語");
INSERT INTO languages (`language_name`, `native_name`) VALUES ("Zulu", "isiZulu");
